/*
SPDX-FileCopyrightText: 2026 M5Stack Technology CO LTD
SPDX-License-Identifier: MIT
*/

// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package device

import (
	"stackChan/api/device"
)

type ControllerV1 struct{}

func NewV1() device.IDeviceV1 {
	return &ControllerV1{}
}

type ControllerV2 struct{}

func NewV2() device.IDeviceV2 {
	return &ControllerV2{}
}
