/*
SPDX-FileCopyrightText: 2026 M5Stack Technology CO LTD
SPDX-License-Identifier: MIT
*/

// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package admin

import (
	"stackChan/api/admin"
)

type ControllerV1 struct{}

func NewV1() admin.IAdminV1 {
	return &ControllerV1{}
}
