/*
SPDX-FileCopyrightText: 2026 M5Stack Technology CO LTD
SPDX-License-Identifier: MIT
*/

// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package friend

import (
	"stackChan/api/friend"
)

type ControllerV1 struct{}

func NewV1() friend.IFriendV1 {
	return &ControllerV1{}
}
