/*
SPDX-FileCopyrightText: 2026 M5Stack Technology CO LTD
SPDX-License-Identifier: MIT
*/

// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package xiaozhi

import (
	"stackChan/api/xiaozhi"
)

type ControllerV1 struct{}

func NewV1() xiaozhi.IXiaozhiV1 {
	return &ControllerV1{}
}
