/*
SPDX-FileCopyrightText: 2026 M5Stack Technology CO LTD
SPDX-License-Identifier: MIT
*/

// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package stackchandevice

import (
	"stackChan/api/stackchandevice"
)

type ControllerV2 struct{}

func NewV2() stackchandevice.IStackchandeviceV2 {
	return &ControllerV2{}
}
