/*
SPDX-FileCopyrightText: 2026 M5Stack Technology CO LTD
SPDX-License-Identifier: MIT
*/

// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package user

import (
	"stackChan/api/user"
)

type ControllerV2 struct{}

func NewV2() user.IUserV2 {
	return &ControllerV2{}
}
