/*
SPDX-FileCopyrightText: 2026 M5Stack Technology CO LTD
SPDX-License-Identifier: MIT
*/

// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"stackChan/internal/dao/internal"
)

// appStoreDao is the data access object for the table app_store.
// You can define custom methods on it to extend its functionality as needed.
type appStoreDao struct {
	*internal.AppStoreDao
}

var (
	// AppStore is a globally accessible object for table app_store operations.
	AppStore = appStoreDao{internal.NewAppStoreDao()}
)

// Add your custom methods and functionality below.
