/*
SPDX-FileCopyrightText: 2026 M5Stack Technology CO LTD
SPDX-License-Identifier: MIT
*/

// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"stackChan/internal/dao/internal"
)

// devicePanoDao is the data access object for the table device_pano.
// You can define custom methods on it to extend its functionality as needed.
type devicePanoDao struct {
	*internal.DevicePanoDao
}

var (
	// DevicePano is a globally accessible object for table device_pano operations.
	DevicePano = devicePanoDao{internal.NewDevicePanoDao()}
)

// Add your custom methods and functionality below.
