/*
SPDX-FileCopyrightText: 2026 M5Stack Technology CO LTD
SPDX-License-Identifier: MIT
*/

// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"stackChan/internal/dao/internal"
)

// deviceDanceDao is the data access object for the table device_dance.
// You can define custom methods on it to extend its functionality as needed.
type deviceDanceDao struct {
	*internal.DeviceDanceDao
}

var (
	// DeviceDance is a globally accessible object for table device_dance operations.
	DeviceDance = deviceDanceDao{internal.NewDeviceDanceDao()}
)

// Add your custom methods and functionality below.
