/*
SPDX-FileCopyrightText: 2026 M5Stack Technology CO LTD
SPDX-License-Identifier: MIT
*/

// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"stackChan/internal/dao/internal"
)

// devicePostDao is the data access object for the table device_post.
// You can define custom methods on it to extend its functionality as needed.
type devicePostDao struct {
	*internal.DevicePostDao
}

var (
	// DevicePost is a globally accessible object for table device_post operations.
	DevicePost = devicePostDao{internal.NewDevicePostDao()}
)

// Add your custom methods and functionality below.
