/*
SPDX-FileCopyrightText: 2026 M5Stack Technology CO LTD
SPDX-License-Identifier: MIT
*/

// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"stackChan/internal/dao/internal"
)

// deviceFriendDao is the data access object for the table device_friend.
// You can define custom methods on it to extend its functionality as needed.
type deviceFriendDao struct {
	*internal.DeviceFriendDao
}

var (
	// DeviceFriend is a globally accessible object for table device_friend operations.
	DeviceFriend = deviceFriendDao{internal.NewDeviceFriendDao()}
)

// Add your custom methods and functionality below.
