/*
SPDX-FileCopyrightText: 2026 M5Stack Technology CO LTD
SPDX-License-Identifier: MIT
*/

// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"stackChan/internal/dao/internal"
)

// deviceDao is the data access object for the table device.
// You can define custom methods on it to extend its functionality as needed.
type deviceDao struct {
	*internal.DeviceDao
}

var (
	// Device is a globally accessible object for table device operations.
	Device = deviceDao{internal.NewDeviceDao()}
)

// Add your custom methods and functionality below.
